import DemoForm from './DemoForm';
import './demo.css';

export const metadata={title:'Book a demo & product guide | Recruit AI',description:'Explore Recruit AI resume screening, interviews and candidate reports. Request a walkthrough for your hiring team.'};
const docs=[
  ['01','Create your hiring workspace','Start with a role','Create your workspace, add a job title and describe the role, required skills and experience. Clear criteria give your team a consistent starting point for screening.','Your job description becomes the reference for candidate review.'],
  ['02','Resume intelligence','Understand the match','Add candidates and their resumes to a role. Review relevant experience, skill matches and gaps alongside the supporting resume evidence.','Review the reasoning alongside the score before shortlisting.'],
  ['03','AI interviews','Go beyond the resume','Set up an interview and share the candidate link. Review candidate responses and the available interview evaluation with your hiring team.','Use the responses to identify strengths and useful follow-up questions.'],
  ['04','Candidate discovery','Find people worth a conversation','Search your talent pool against your hiring requirements. Open candidate profiles to review their career evidence and suitability for the role.','Keep the role requirements specific so matches are easier to assess.'],
  ['05','Reports & decisions','Bring the evidence together','Review resume analysis, interview signals and team scorecards. Track candidate progress and use the evidence to decide the next step.','Scores support a decision; your hiring team makes the final call.'],
];
export default function DemoPage(){return <main className="demoPage" id="top">
  <header className="nav"><a className="logo" href="/"><span><img src="/recruit-ai-logo.png" alt=""/></span>Recruit <i>AI</i></a><nav aria-label="Demo navigation"><a href="#guide">Product guide</a><a href="/#reports">Reports</a></nav><div><a className="darkButton" href="#request-demo">Book a demo ↗</a></div></header>
  <section className="demoHero"><p className="available"><b/>YOUR GUIDE TO RECRUIT AI</p><h1>Better hiring starts<br/><em>with a clearer picture.</em></h1><p>Explore how Recruit AI connects your roles, resumes, interviews and candidate insights. Then let’s walk through your hiring needs together.</p><div className="heroBtns"><a className="gradientBtn" href="#request-demo">Book your personal demo ↗</a><a className="outlineBtn" href="#guide">Read the product guide ↓</a></div><div className="demoPills"><span>Resume intelligence</span><span>AI interviews</span><span>Candidate reports</span></div></section>
  <section className="demoGuide" id="guide"><aside><p className="reportEyebrow">THE PRODUCT GUIDE</p><h2>From first resume<br/>to <em>next steps.</em></h2><nav aria-label="Guide chapters">{docs.map(([n,title])=><a href={'#chapter-'+n} key={n}><small>{n}</small>{title}</a>)}</nav><a className="demoBack" href="/">← Back to the landing page</a></aside><div className="demoChapters">{docs.map(([n,title,heading,body,note])=><article id={'chapter-'+n} key={n}><p className="reportEyebrow">{n} / {title}</p><h3>{heading}</h3><p>{body}</p><div className="demoDocNote"><span>↗</span>{note}</div></article>)}</div></section>
  <section id="request-demo" className="demoBooking"><div><p className="reportEyebrow">LET’S TALK HIRING</p><h2>Your roles.<br/>Your team.<br/><em>Your Recruit AI demo.</em></h2><p>Tell us a little about your company and what you’re hiring for. We’ll get back to you to arrange a walkthrough.</p><div className="demoAgenda"><b>What we’ll cover</b><p>01 &nbsp; Your current hiring process</p><p>02 &nbsp; Screening, interviews and reports</p><p>03 &nbsp; Questions and next steps</p></div><a className="demoEmail" href="mailto:aadilhussainkhan7@gmail.com">aadilhussainkhan7@gmail.com ↗</a></div><DemoForm/></section>
  <div className="demoFooter"><a className="logo" href="/">Recruit <i>AI</i></a><span>Built for thoughtful hiring teams.</span><a href="/">Back to home ↗</a></div>
</main>}
