'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { evaluateInterviewAnswers } from '../../../../../lib/nim-interview';
import { getJobForWorkspace, canManageCandidates } from '../../../../../lib/recruit-data';
import { createRecord, listRecords, pbFilterValue, updateRecord } from '../../../../../lib/pocketbase';
import { requireWorkspace } from '../../../../../lib/workspace-page';

export async function evaluateInterviewAction(formData){const interviewId=String(formData.get('interviewId')||'');const route=`/dashboard/interviews/${encodeURIComponent(interviewId)}/candidate-response`;const {workspace,membership,userId}=await requireWorkspace();if(!canManageCandidates(membership))redirect(`${route}?notice=forbidden`);const found=await listRecords('interviews',{filter:`workspace = "${pbFilterValue(workspace.id)}" && id = "${pbFilterValue(interviewId)}" && status = "completed"`,perPage:1});const interview=found.items?.[0];if(!interview||!Array.isArray(interview.candidate_answers)||!interview.candidate_answers.length)redirect(`${route}?notice=not-ready`);const job=await getJobForWorkspace(workspace.id,interview.job);if(!job)redirect('/dashboard/interviews');let record;try{record=await createRecord('interview_ai_evaluations',{workspace:workspace.id,interview:interview.id,application:interview.application,requested_by_clerk_id:userId,status:'processing'});const result=await evaluateInterviewAnswers({job,interview});await updateRecord('interview_ai_evaluations',record.id,{status:'completed',recommendation:result.data.recommendation,confidence:result.data.confidence,structured_data:result.data,model:result.model});await createRecord('activities',{workspace:workspace.id,actor_clerk_user_id:userId,entity_type:'interview',entity_id:interview.id,action:'interview.ai_evaluated',metadata:{evaluationId:record.id,recommendation:result.data.recommendation}}).catch(()=>null)}catch(error){if(record)await updateRecord('interview_ai_evaluations',record.id,{status:'failed',error_message:String(error?.message||'Evaluation failed').slice(0,1000)}).catch(()=>null);redirect(`${route}?notice=evaluation-failed`)}revalidatePath(route);redirect(`${route}?notice=evaluation-complete`)}

export async function decideInterviewCandidateAction(formData){const interviewId=String(formData.get('interviewId')||''),decision=String(formData.get('decision')||''),note=String(formData.get('note')||'').trim().slice(0,1000),route=`/dashboard/interviews/${encodeURIComponent(interviewId)}/candidate-response`;const {workspace,membership,userId}=await requireWorkspace();if(!canManageCandidates(membership)||!['advance','hold','reject'].includes(decision))redirect(`${route}?notice=invalid-decision`);const found=await listRecords('interviews',{filter:`workspace = "${pbFilterValue(workspace.id)}" && id = "${pbFilterValue(interviewId)}"`,perPage:1});const interview=found.items?.[0];if(!interview)redirect('/dashboard/interviews');const records=await listRecords('applications',{filter:`workspace = "${pbFilterValue(workspace.id)}" && id = "${pbFilterValue(interview.application)}"`,perPage:1});const application=records.items?.[0];if(!application)redirect('/dashboard/interviews');const now=new Date().toISOString(),stage=decision==='advance'?'interview':decision==='hold'?'screening':'rejected',status=decision==='reject'?'rejected':'active',notes=Array.isArray(application.notes)?application.notes:[];await updateRecord('applications',application.id,{stage,status,last_activity_at:now,stage_changed_at:now,notes:[...notes,{text:`Interview review: ${decision}${note?` — ${note}`:''}`,author:userId,created:now}]});await createRecord('activities',{workspace:workspace.id,actor_clerk_user_id:userId,entity_type:'application',entity_id:application.id,action:'interview.human_decision_recorded',metadata:{interviewId,decision,note}}).catch(()=>null);revalidatePath('/dashboard/interviews');revalidatePath(route);redirect(`${route}?notice=decision-saved`)}
