 'use client';
import {useState} from 'react';
const labels={'strong-yes':'Strong yes',yes:'Yes',mixed:'Mixed',no:'No','strong-no':'Strong no'};
export default function InterviewDNA({data,answers}){
 const [tab,setTab]=useState('overview');
 const skills=Array.isArray(data?.skill_signals)?data.skill_signals:[];
 const evidence=(items,empty)=>Array.isArray(items)&&items.length?items.map((item,i)=><article className="dnaEvidence" key={i}><h3>{item.claim}</h3>{item.evidence&&<blockquote>{item.evidence}</blockquote>}</article>):<p className="dnaMuted">{empty}</p>;
 return <section className="surfaceCard interviewDNA"><div className="dnaHeading"><div><p className="pageEyebrow">INTERVIEW DNA</p><h2>The interview, at a glance.</h2></div><span className="dnaBadge">{answers.length} answers saved</span></div>
 <div className="dnaMetrics"><div><small>AI recommendation</small><strong>{labels[data?.recommendation]||'Awaiting evaluation'}</strong></div><div><small>Skills supported</small><strong>{data?`${skills.filter(s=>s.status==='supported').length} / ${skills.length}`:'?'}</strong></div><div><small>AI confidence ? not a score</small><strong>{Number.isFinite(data?.confidence)?`${Math.round(data.confidence*100)}%`:'?'}</strong></div></div>
 <div className="dnaTabs" role="tablist" aria-label="Interview details">{[['overview','Overview'],['skills','Skills'],['answers','Answers']].map(([id,label],i)=><button key={id} id={`dna-tab-${id}`} role="tab" aria-selected={tab===id} aria-controls={`dna-panel-${id}`} tabIndex={tab===id?0:-1} onClick={()=>setTab(id)} onKeyDown={e=>{const tabs=['overview','skills','answers'];let next;if(e.key==='ArrowRight')next=tabs[(i+1)%3];if(e.key==='ArrowLeft')next=tabs[(i+2)%3];if(e.key==='Home')next=tabs[0];if(e.key==='End')next=tabs[2];if(next){e.preventDefault();setTab(next);document.getElementById(`dna-tab-${next}`)?.focus()}}}>{label}{id==='answers'&&<span>{answers.length}</span>}</button>)}</div>
 <div role="tabpanel" id={`dna-panel-${tab}`} aria-labelledby={`dna-tab-${tab}`} tabIndex={0} className="dnaPanel">
 {tab==='overview'&&(data?<><p className="dnaSummary">{data.summary}</p><div className="dnaColumns"><section><h2>Strengths</h2>{evidence(data.strengths,'No strengths recorded yet.')}</section><section><h2>Explore further</h2>{evidence(data.risks,'No follow-up risks recorded.')}</section></div><p className="dnaMuted">AI findings are based on submitted answers. Review the evidence before making a hiring decision.</p></>:<p className="dnaSummary">Answers are saved. Evaluate the interview to see a recommendation, strengths and skill evidence.</p>)}
 {tab==='skills'&&(skills.length?<div className="dnaSkills">{skills.map((s,i)=><article key={i}><div><h3>{s.skill}</h3><span className={`dnaBadge ${s.status==='supported'?'supported':''}`}>{s.status==='supported'?'Supported':s.status==='not-demonstrated'?'Not demonstrated':'Unclear'}</span></div>{s.evidence&&<blockquote>{s.evidence}</blockquote>}</article>)}<p className="dnaMuted">Missing evidence is a follow-up opportunity, not a negative score.</p></div>:<p className="dnaMuted">No skill signals available yet.</p>)}
 {tab==='answers'&&<div className="dnaAnswers">{answers.map((a,i)=><details key={a.question_id||i} open={i===0}><summary><span>Q{String(i+1).padStart(2,'0')}</span>{a.prompt}</summary><p>{a.answer}</p></details>)}</div>}
 </div></section>;
}
