'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import './voice.css';

export default function VoiceInterview({token,title,questions,submit,recordEvent,requestFollowup}) {
  const [step,setStep]=useState('check'),[stream,setStream]=useState(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[speaking,setSpeaking]=useState(false),[index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[listening,setListening]=useState(false),[supported,setSupported]=useState(false),[paused,setPaused]=useState(false),[pending,setPending]=useState(false);
  const rec=useRef(null),tracks=useRef(null),speech=useRef(null),fullscreen=useRef(false);
  const [draftReady,setDraftReady]=useState(false),[submitted,setSubmitted]=useState(false),[questionList,setQuestionList]=useState(questions),[adapting,setAdapting]=useState(false);
  const draftKey='recruit-interview-draft:'+token;
  useEffect(()=>{try{const draft=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(draft&&Date.now()-draft.savedAt<86400000&&draft.questions===JSON.stringify(questions)){setAnswers(draft.answers||{});setIndex(Math.max(0,Math.min(questions.length-1,draft.index||0)));}}catch{}setDraftReady(true);},[draftKey]);
  useEffect(()=>{if(!draftReady||submitted)return;try{sessionStorage.setItem(draftKey,JSON.stringify({answers,index,savedAt:Date.now(),questions:JSON.stringify(questions)}));}catch{setError('Draft storage is unavailable. Keep this tab open until you submit.');}},[answers,index,draftReady,submitted,draftKey]);
  const current=questionList[index];
  const probed=useRef(new Set());
  useEffect(()=>{if(index<1||!requestFollowup)return;const previous=questionList[index-1],answer=answers[previous?.id]||'';if(!previous||previous.adaptive||answer.trim().length<20||probed.current.has(previous.id))return;probed.current.add(previous.id);setAdapting(true);requestFollowup(token,previous.id,answer).then(result=>{if(result?.question)setQuestionList(list=>[...list.slice(0,index),result.question,...list.slice(index)])}).finally(()=>setAdapting(false));},[index,questionList,answers,requestFollowup,token]);
  const intro=`Hello, I am Ava, your AI interview guide. Welcome to ${title}. I will ask ${questions.length} planned questions and may ask relevant follow-ups. Share specific examples of your work, your approach and results. You can review and correct your transcript before submitting. The hiring team will review your answers. Let's begin when you are ready.`;
  useEffect(()=>{setSupported(Boolean(window.SpeechRecognition||window.webkitSpeechRecognition));return()=>{rec.current?.abort();tracks.current?.getTracks().forEach(t=>t.stop());window.speechSynthesis?.cancel()}},[]);
  useEffect(()=>{if(step!=='interview')return;const pause=()=>{if(document.hidden||(fullscreen.current&&!document.fullscreenElement)){rec.current?.stop();window.speechSynthesis?.cancel();setPaused(true);recordEvent?.(token,document.hidden?'tab-hidden':'fullscreen-exit')}};document.addEventListener('visibilitychange',pause);document.addEventListener('fullscreenchange',pause);return()=>{document.removeEventListener('visibilitychange',pause);document.removeEventListener('fullscreenchange',pause)}},[step]);
  async function check(){setError('');setStream(null);try{tracks.current?.getTracks().forEach(t=>t.stop());const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});tracks.current=s;setStream(s)}catch{setError('Allow camera and microphone access in your browser, then retry. HTTPS or localhost is required.')}}
  const speak=useCallback((text,done)=>{
    const synth=window.speechSynthesis;
    if(!synth){setError('Audio playback unavailable. You can read the question and type your answer.');return}
    speech.current=null;synth.cancel();setSpeaking(false);
    const voices=synth.getVoices();
    const preferredVoice=voices.find(v=>/^en/i.test(v.lang)&&/\b(ava|samantha|zira|susan|hazel|jenny|aria|sonia|natasha|heera|neerja|female)\b/i.test(v.name));
    const voice=preferredVoice||voices.find(v=>/^en/i.test(v.lang))||voices[0];
    if(!voice){setError('Voice playback is unavailable on this device. You can read the questions and type your answers.');return}
    const u=new SpeechSynthesisUtterance(text);speech.current=u;u.voice=voice;u.lang=voice.lang;u.rate=.95;
    u.onend=()=>{if(speech.current!==u)return;setSpeaking(false);done?.()};
    u.onerror=e=>{if(speech.current!==u)return;setSpeaking(false);if(!['canceled','interrupted'].includes(e.error))setError('Voice playback could not start. Select Read question aloud to retry.')};
    setError('');setSpeaking(true);synth.speak(u);
  },[]);
  useEffect(()=>{
    const synth=window.speechSynthesis;
    if(step!=='interview'||paused||!synth)return;
    let played=false;
    const play=()=>{if(played)return;played=true;speak(current.prompt)};
    const loaded=()=>{if(synth.getVoices().length)play()};
    synth.addEventListener('voiceschanged',loaded);
    const timer=setTimeout(play,800);loaded();
    return()=>{clearTimeout(timer);synth.removeEventListener('voiceschanged',loaded);speech.current=null;synth.cancel();setSpeaking(false)};
  },[step,paused,index,current.prompt,speak]);
  async function begin(){setError('');fullscreen.current=false;try{if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();fullscreen.current=true}}catch{setError('Fullscreen is unavailable. You can continue in this window.')}setPaused(false);setStep('interview')}
  async function advance(){setAdapting(true);try{const followup=await requestFollowup?.(token,current.id,answers[current.id]||'');if(followup?.question)setQuestionList(list=>[...list.slice(0,index+1),followup.question,...list.slice(index+1)]);setIndex(i=>i+1)}finally{setAdapting(false)}}
  function listen(){setError('');window.speechSynthesis?.cancel();setSpeaking(false);const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return;const r=new R();rec.current=r;const id=current.id,base=answers[id]||'';r.continuous=true;r.interimResults=false;r.lang='en-IN';r.onresult=e=>{const text=Array.from(e.results).filter(x=>x.isFinal).map(x=>x[0].transcript).join(' ');setAnswers(a=>({...a,[id]:[base,text].filter(Boolean).join(' ').slice(0,5000)}))};r.onerror=()=>setError('Transcription stopped. Retry or type your answer; existing text is preserved.');r.onend=()=>setListening(false);try{r.start();setListening(true)}catch{setError('Microphone could not start. Retry.');setListening(false)}}
  if(submitted)return <main className="voiceExperience"><section className="voicePanel"><h1>Thank you. Your interview is submitted.</h1><p>Your answers have been saved.</p></section></main>;
  const preview=<div className="voicePreview">{stream?<video autoPlay muted playsInline ref={el=>{if(el)el.srcObject=stream}}/>:<span>Your camera preview</span>}</div>;
  return <main className={`voiceExperience voiceStep-${step}`}><header><b>recruit<span>ai</span></b><span>{step==='check'?'01 / Device check':step==='intro'?'02 / Meet your interviewer':`03 / Interview · ${index+1} of ${questions.length}`}</span></header><div className="voiceWorkspace">{step==='interview'&&<aside className="voiceStage"><div className="voiceStageTop"><span className="voiceLiveDot"/> LIVE SESSION<span className="voiceStageTag">AI INTERVIEW</span></div><div className={`voiceHost ${speaking?'isSpeaking':''}`}><div className="voiceHostHalo"><div className="voiceHostCore">A</div></div><h2>Ava</h2><p>{speaking?'Speaking to you':listening?'Listening to your answer':'Your AI interviewer'}</p><div className="voiceWave" aria-hidden="true">{[1,2,3,4,5,6,7].map(x=><i key={x}/>)}</div></div><div className="voiceSelf">{preview}<span>You <b>{stream ? 'Camera connected' : 'Camera off'}</b></span></div><div className="voiceStageFooter">Take your time. Share your experience.</div></aside>}<section className="voicePanel">
    {error&&<p className="voiceNotice" role="alert">{error}</p>}
    {step==='check'&&<><small>YOUR SPACE TO SHINE</small><h1>A little preparation.<br/>A great conversation.</h1><p>Check your camera and microphone before meeting your AI interviewer.</p>{preview}<p>{stream?'Camera and microphone connected.':'Devices have not been checked yet.'}</p><button onClick={check}>{stream?'Check again':'Check camera & microphone'}</button><button onClick={()=>{setError('');setStep('intro')}}>{stream ? 'Continue' : 'Continue with typed answers'}</button><p className="voiceFine">Camera preview stays on your device. Voice transcription may send audio to your browser provider. Your reviewed answers are stored for the hiring team. Drafts stay in this browser tab for up to 24 hours. Tab switches and fullscreen exits are logged for the hiring team; these signals alone do not determine your result. {supported?'Voice transcription is available.':'Voice recognition is unavailable here; typed answers are supported.'}</p></>}
    {step==='intro'&&<><div className="voiceOrb">A</div><small>MEET YOUR AI INTERVIEWER</small><h1>Hello, I'm Ava.</h1><p>{intro}</p><button disabled={speaking} onClick={()=>speak(intro,()=>setReady(true))}>{speaking?'Introduction playing…':'Play introduction'}</button><button disabled={!ready||speaking} onClick={begin}>Start interview</button><button className="voiceText" onClick={()=>{window.speechSynthesis?.cancel();setSpeaking(false);setReady(true)}}>Accessibility: I have read the introduction</button></>}
    {step==='interview'&&<>{paused?<><h1>Interview paused.</h1><p>Resume when you are ready. Your answers are still here.</p><button onClick={begin}>Resume interview</button></>:<><div className="voiceQuestionHeader"><small>QUESTION {index+1} / {questions.length}</small><button disabled={listening||speaking} onClick={()=>speak(current.prompt)}>Read question aloud</button></div><h1>{current.prompt}</h1><progress value={index+1} max={questions.length}/><label htmlFor="answer" className="voiceAnswerLabel"><span>Your response</span><small>LIVE TRANSCRIPT</small></label><textarea id="answer" maxLength={5000} disabled={listening} value={answers[current.id]||''} onChange={e=>setAnswers(a=>({...a,[current.id]:e.target.value}))} placeholder="Speak or type a specific example from your experience."/><p aria-live="polite">{listening?'Listening… stop when finished.':'Your transcript can be edited.'}</p><div className="voiceControls"><button className={`voiceMicButton ${listening?'isListening':''}`} disabled={!supported} onClick={()=>listening?rec.current?.stop():listen()}>{listening?'Stop microphone':'Start speaking'}</button><button className="voiceBackButton" disabled={index===0||listening||speaking} onClick={()=>setIndex(i=>i-1)}>Back</button>{index<questions.length-1?<button className="voiceNextButton" disabled={listening||speaking||(answers[current.id]||'').trim().length<20} onClick={()=>setIndex(i=>i+1)}>Next question <span aria-hidden="true">→</span></button>:<form action={async fd=>{setPending(true);try{const result=await submit(fd);if(result?.error){setError(result.error);return;}setSubmitted(true);try{sessionStorage.removeItem(draftKey)}catch{}tracks.current?.getTracks().forEach(t=>t.stop());window.speechSynthesis?.cancel();if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});}catch{setError('Could not submit. Your draft is preserved; please retry.');}finally{setPending(false)}}}><input type="hidden" name="token" value={token}/>{questions.map(q=><input key={q.id} type="hidden" name={`answer-${q.id}`} value={answers[q.id]||''}/>)}<button className="voiceNextButton" disabled={pending||listening||speaking||questions.some(q=>(answers[q.id]||'').trim().length<20)}>{pending?'Submitting…':'Submit interview'}</button></form>}</div><p className="voiceFine">At least 20 characters per answer. Stay in this tab; leaving fullscreen pauses the interview.</p></>}</>}
  </section></div></main>;
}
