import test from 'node:test';import assert from 'node:assert/strict';
import {validateInterviewEvaluation,buildInterviewQuestions,canSubmitScorecard} from '../lib/interview-validation.mjs';
test('interview AI strips fabricated quotes and malformed nested values',()=>{
 const result=validateInterviewEvaluation({recommendation:'strong-yes',confidence:.99,summary:'Excellent',strengths:[{claim:'Invented experience',evidence:'Led a team of 100 people'},null,{claim:{bad:true},evidence:'I built reliable software'}],risks:[{claim:'Unsupported risk',evidence:{bad:true}}],skill_signals:[null,{skill:{bad:true}},{skill:'JavaScript',status:'supported',evidence:'Invented quote'}]},[{question_id:'skill-0',prompt:'Describe a project where you used JavaScript. What was your contribution and result?',answer:'I built reliable software using JavaScript.'}]);
 assert.deepEqual(result.strengths,[]);assert.deepEqual(result.risks,[]);assert.equal(result.skill_signals[0].status,'unclear');assert.equal(result.recommendation,'mixed');assert.ok(result.confidence<=.5);
});
test('interview AI preserves actual evidence and rejects invalid top-level values',()=>{
 const result=validateInterviewEvaluation({recommendation:'yes',confidence:.8,summary:'Relevant evidence',strengths:[{claim:'Built software',evidence:'I built reliable software'}],risks:[],skill_signals:[{skill:'JavaScript',status:'supported',evidence:'I built reliable software using JavaScript'}]},[{question_id:'skill-0',prompt:'Describe a project where you used JavaScript. What was your contribution and result?',answer:'I built reliable software using JavaScript.'}]);assert.equal(result.strengths.length,1);assert.equal(result.skill_signals[0].status,'supported');assert.equal(result.recommendation,'yes');assert.match(result.summary,/Evidence-backed skills: JavaScript/);assert.throws(()=>validateInterviewEvaluation({recommendation:'yes',confidence:'1',summary:'bad'},[]));
});
test('unrelated exact quotes cannot manufacture skills, claims, recommendations or summaries',()=>{
 const result=validateInterviewEvaluation({recommendation:'strong-yes',confidence:.99,summary:'Expert Kubernetes engineer with deep production experience.',strengths:[{claim:'Operated Kubernetes at massive scale',evidence:'I coordinated weekly meetings'}],risks:[],skill_signals:[{skill:'Kubernetes',status:'supported',evidence:'I coordinated weekly meetings'}]},[{question_id:'skill-0',prompt:'Describe a project where you used Kubernetes. What was your contribution and result?',answer:'I coordinated weekly meetings and wrote clear documentation for the team.'}]);
 assert.deepEqual(result.strengths,[]);assert.equal(result.skill_signals[0].status,'unclear');assert.equal(result.recommendation,'mixed');assert.ok(result.confidence<=.4);assert.doesNotMatch(result.summary,/expert|production experience/i);
});
test('negated and learning-only skill mentions are never supported',()=>{
 const negated=validateInterviewEvaluation({recommendation:'yes',confidence:.9,summary:'x',strengths:[],risks:[],skill_signals:[{skill:'Kubernetes',status:'supported',evidence:'I have never used Kubernetes in production'}]},[{question_id:'skill-0',prompt:'Describe a project where you used Kubernetes. What was your contribution and result?',answer:'I have never used Kubernetes in production, but I am interested in it.'}]);
 assert.equal(negated.skill_signals[0].status,'not-demonstrated');assert.equal(negated.recommendation,'mixed');
 const learning=validateInterviewEvaluation({recommendation:'yes',confidence:.9,summary:'x',strengths:[],risks:[],skill_signals:[{skill:'React',status:'supported',evidence:'I am learning React through a beginner tutorial'}]},[{question_id:'skill-0',prompt:'Describe a project where you used React. What was your contribution and result?',answer:'I am learning React through a beginner tutorial and might use it later.'}]);
 assert.equal(learning.skill_signals[0].status,'unclear');assert.equal(learning.recommendation,'mixed');
});
test('skill evidence must come from its matching skill question',()=>{
 const result=validateInterviewEvaluation({recommendation:'yes',confidence:.9,summary:'x',strengths:[],risks:[],skill_signals:[{skill:'Kubernetes',status:'supported',evidence:'I used Kubernetes to deploy three services'}]},[{question_id:'experience',prompt:'Describe your most relevant experience for Engineer.',answer:'I used Kubernetes to deploy three services.'},{question_id:'skill-0',prompt:'Describe a project where you used Kubernetes. What was your contribution and result?',answer:'I mostly coordinated the project.'}]);
 assert.equal(result.skill_signals[0].status,'unclear');assert.equal(result.skill_signals[0].evidence,'');
});
test('team-only exposure and keyword repetition do not become personal competence',()=>{
 const teamOnly=validateInterviewEvaluation({recommendation:'strong-yes',confidence:1,summary:'Expert',strengths:[{claim:'Used Kubernetes',evidence:'Our team used Kubernetes and I coordinated weekly meetings'}],risks:[],skill_signals:[{skill:'Kubernetes',status:'supported',evidence:'Our team used Kubernetes and I coordinated weekly meetings'}]},[{question_id:'skill-0',prompt:'Describe a project where you used Kubernetes. What was your contribution and result?',answer:'Our team used Kubernetes and I coordinated weekly meetings. Kubernetes Kubernetes Kubernetes.'}]);
 assert.equal(teamOnly.skill_signals[0].status,'unclear');assert.deepEqual(teamOnly.strengths,[]);assert.equal(teamOnly.recommendation,'mixed');
});
test('direct invite question generation always creates usable questions',()=>{const q=buildInterviewQuestions({title:'Engineer',must_have_skills:['JavaScript','SQL']});assert.equal(q.length,4);assert.equal(new Set(q.map(x=>x.id)).size,q.length);assert.ok(q.every(x=>x.required&&x.prompt.length>20));});
test('active interviewers can score; disabled members cannot',()=>{assert.equal(canSubmitScorecard({role:'interviewer',status:'active'}),true);assert.equal(canSubmitScorecard({role:'hiring-manager',status:'active'}),true);assert.equal(canSubmitScorecard({role:'interviewer',status:'disabled'}),false);});
