const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {build}=require('./ui-interactions.cjs');
const root=path.resolve(__dirname,'..');
const source=`
import React from 'react';import {createRoot} from 'react-dom/client';
import AppShell from './app/dashboard/components/AppShell';import Landing from './app/page';
import JobForm from './app/dashboard/jobs/JobForm';import CandidateForm from './app/dashboard/candidates/CandidateForm';
import InterviewForm from './app/dashboard/interviews/new/InterviewForm';
import {WorkspaceForm,InviteForm} from './app/dashboard/settings/SettingsForms';
import VoiceInterview from './app/interview/[token]/VoiceInterview';
import CopyLink from './app/dashboard/components/CopyLink';
import EmailForm from './app/dashboard/candidates/[candidateId]/communication/EmailForm';
const root=createRoot(document.getElementById('root'));
const long='SeniorEngineeringLeadershipCandidateWithAnUnusuallyLongName';
function Lists(){return <div className="productPage"><header className="pageHeading"><div><h1>Candidates and interviews</h1><p>Manage your recruiting pipeline on any device.</p></div><a className="primaryAction" href="#">Add candidate +</a></header><form className="moduleToolbar candidateToolbar"><div><strong>128</strong><span>total candidates</span></div><label className="moduleSearch"><input aria-label="Filter candidates" placeholder="Name, email or role"/></label><select aria-label="Status"><option>Do not contact</option></select><select aria-label="Source"><option>Career site</option></select><button>Apply</button></form><section className="dataSurface"><div className="dataHeader four"><span>Candidate</span><span>Role</span><span>Location</span><span>Status</span></div>{[1,2,3].map(id=><div className="dataRow four" key={id}><div className="candidateIdentity"><div><b>{long}</b><small>{long.toLowerCase()}@example.com</small></div></div><span>Senior software engineer</span><span>Bengaluru, India</span><form><select aria-label={'Interview status '+id}><option>scheduled</option><option>completed</option></select><button>Save</button></form></div>)}</section><nav className="moduleToolbar"><a href="#">Previous</a><span>Page 1 of 8 · 128 records</span><a href="#">Next</a></nav></div>}
function Settings(){return <div className="settingsGrid"><section className="surfaceCard settingsCard"><h2>Workspace profile</h2><WorkspaceForm workspace={{name:long,company_size:'11-50',website:'https://example.com'}}/></section><section className="surfaceCard settingsCard"><h2>Invite team member</h2><InviteForm/><CopyLink url={'https://example.com/dashboard/join/'+long+long}/></section></div>}
function Analytics(){return <div className="productPage"><h1>Hiring analytics</h1><section className="metricGrid">{['Open roles','Active pipeline','Hired','Conversion'].map(x=><article key={x}><small>{x}</small><strong>1,250</strong><span>Applications in this workspace</span></article>)}</section><div className="analyticsGrid"><section className="surfaceCard"><h2>Pipeline health</h2><p>{long+long}</p></section><section className="surfaceCard"><h2>Candidate sources</h2></section></div></div>}
function Application(){return <main className="candidateWelcome"><header className="welcomeTop"><a>recruitai</a><span>YOUR NEXT CHAPTER STARTS HERE</span></header><div className="welcomeLayout"><aside className="welcomeStory"><h1>Great work starts with a great conversation.</h1><div className="welcomeRole"><h2>{long}</h2></div></aside><section className="welcomeFormCard"><h2>First, a little about you.</h2><form><div className="welcomeFieldPair"><label>First name<input/></label><label>Last name<input/></label></div><label>Email<select><option>{long.toLowerCase()}@example.com</option></select></label><label className="welcomeConsent"><input type="checkbox"/><span>I consent to storing and processing my details for this application.</span></label><button className="welcomeContinue">Continue to device check →</button></form></section></div></main>}
window.show=name=>{const content=name==='job'?<JobForm/>:name==='candidate'?<CandidateForm/>:name==='settings'?<Settings/>:name==='analytics'?<Analytics/>:name==='schedule'?<section className="surfaceCard interviewForm"><InterviewForm applications={[{id:'a1',job:'j1',candidate:'c1',jobTitle:long,candidateName:long,candidateEmail:'rahul@example.com',stage:'new'}]}/></section>:name==='email'?<section className="surfaceCard communicationShell"><EmailForm candidate={{id:'c1',first_name:'Rahul',email:long+'@example.com'}} templates={{custom:['',''],'interview-invite':['Interview invitation','Hi Rahul, we would like to invite you.']}}/></section>:<Lists/>;root.render(name==='landing'?<Landing/>:name==='voice'?<VoiceInterview key={name} token="mobile-test" title={long} questions={[{id:'q1',prompt:'Tell us about your most relevant experience and the outcome of your work.'}]} submit={async()=>({completed:true})}/>:name==='application'?<Application/>:<AppShell key={name} workspaceName={long} userName="Recruiter">{content}</AppShell>);};
`;
const bundle=build(source);
const css=['app/globals.css','app/dashboard/dashboard.css','app/interview/[token]/voice.css','app/interview/apply/[token]/apply.css','app/mobile.css'].map(p=>fs.readFileSync(path.join(root,p),'utf8').replace(/@import[^;]+;/g,'')).join('\n');
async function main(){const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style></head><body><div id="root"></div><script>'+bundle.replaceAll('</script','<\\/script')+'</script></body></html>')});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];await page.addInitScript(()=>document.addEventListener('click',e=>{if(e.target.closest('a'))e.preventDefault()}));page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'domcontentloaded'});let checks=0;const failures=[];
 for(const width of [320,360,390,430,768,1024,1280]){await page.setViewportSize({width,height:844});for(const screen of ['lists','job','candidate','settings','analytics','schedule','email','application','voice','landing']){await page.evaluate(name=>window.show(name),screen);await page.waitForTimeout(70);const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,culprits:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2&&getComputedStyle(e).visibility!=='hidden').slice(0,6).map(e=>e.className||e.tagName)}));if(overflow.scroll>width+1)failures.push({width,screen,...overflow});checks++;}}
 console.log(JSON.stringify({checks,failures},null,2));await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.show('lists'));await page.getByRole('button',{name:'Open navigation'}).click();assert.equal(await page.getByRole('button',{name:'Open navigation'}).getAttribute('aria-expanded'),'true');await page.getByRole('link',{name:'Jobs',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Open navigation'}).getAttribute('aria-expanded'),'false');await page.getByRole('button',{name:'Open navigation'}).click();await page.keyboard.press('Escape');assert.equal(await page.getByRole('button',{name:'Open navigation'}).getAttribute('aria-expanded'),'false');await page.screenshot({path:'D:/Temp/recruit-mobile-list.png',fullPage:true,animations:"disabled"});
 await page.evaluate(()=>window.show('landing'));await page.getByRole('button',{name:'Open menu'}).click();await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link',{name:'Pricing',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Open menu'}).getAttribute('aria-expanded'),'false');await page.screenshot({path:'D:/Temp/recruit-mobile-landing.png',animations:'disabled'});
 await page.evaluate(()=>window.show('job'));await page.screenshot({path:'D:/Temp/recruit-mobile-job.png',fullPage:true,animations:"disabled"});
 await page.evaluate(()=>window.show('voice'));await page.getByRole('button',{name:'Continue with typed answers'}).click();await page.getByRole('button',{name:'Accessibility: I have read the introduction'}).click();await page.evaluate(()=>{document.documentElement.requestFullscreen=async()=>{throw Error('Unavailable')};Object.defineProperty(window,'speechSynthesis',{configurable:true,value:undefined})});await page.getByRole('button',{name:'Start interview'}).click();await page.getByLabel('Your response').fill('I built reliable software and reviewed the results.');await page.setViewportSize({width:390,height:380});assert(await page.getByRole('button',{name:'Submit interview'}).isEnabled());await page.getByRole('button',{name:'Submit interview'}).scrollIntoViewIfNeeded();assert(await page.getByRole('button',{name:'Submit interview'}).isVisible());await page.setViewportSize({width:390,height:844});await page.screenshot({path:'D:/Temp/recruit-mobile-interview.png',fullPage:true,animations:"disabled"});
 console.log(JSON.stringify({checks,failures,errors},null,2));assert.deepEqual(failures,[]);assert.deepEqual(errors,[]);console.log('PASS responsive layouts, mobile navigation and short-viewport interview controls');
 }finally{await browser?.close();await new Promise(r=>server.close(r))}}
main().catch(e=>{console.error(e);process.exitCode=1});
