'use client';
import {useActionState,useState} from 'react';
import {saveWorkspaceAction,inviteMemberAction,revokeInviteAction,manageMemberAction,switchWorkspaceAction} from './actions';
import CopyLink from '../components/CopyLink';
function Notice({state}){return <p role={state.error?'alert':'status'}>{state.error||state.message||''}</p>;}
export function WorkspaceForm({workspace}) {
 const [state,action,pending]=useActionState(saveWorkspaceAction,{});
 const [values,setValues]=useState(workspace);
 const field=name=>({value:values[name]||'',onChange:e=>setValues(current=>({...current,[name]:e.target.value}))});
 return <form action={action}><label>Name<input name="name" required minLength={2} maxLength={120} {...field('name')}/></label><label>Website<input name="website" type="url" {...field('website')}/></label><label>Company size<select name="company_size" {...field('company_size')}>{['1-10','11-50','51-200','201-500','501-1000','1000+'].map(x=><option key={x}>{x}</option>)}</select></label><Notice state={state}/><button disabled={pending}>{pending?'Saving…':'Save workspace'}</button></form>;
}
export function InviteForm(){const [state,action,pending]=useActionState(inviteMemberAction,{});const [values,setValues]=useState({name:"",email:"",role:"recruiter"});const field=name=>({value:values[name],onChange:e=>setValues(v=>({...v,[name]:e.target.value}))});return <><form action={action}><label>Name<input name="name" {...field("name")} required minLength={2} maxLength={120}/></label><label>Email<input name="email" {...field("email")} type="email" required maxLength={254}/></label><label>Access role<select name="role" {...field("role")}><option value="recruiter">Recruiter</option><option value="hiring-manager">Hiring manager</option><option value="interviewer">Interviewer</option></select></label><p>Create a link to share. The recipient must sign in with this verified email to join. Links expire after seven days.</p><Notice state={state}/><button disabled={pending}>{pending?'Creating…':'Invite team member'}</button></form>{state.path&&<CopyLink path={state.path}/>}</>;}
export function RevokeInvite({id}){const[state,action,pending]=useActionState(revokeInviteAction,{});return <form action={action}><input type="hidden" name="membershipId" value={id}/><button disabled={pending}>{pending?'Revoking…':'Revoke invitation'}</button><Notice state={state}/></form>;}

export function MemberForm({member,isOwner}) {const[state,action,pending]=useActionState(manageMemberAction,{});return <form action={action}><input type="hidden" name="membershipId" value={member.id}/><label>Role<select name="role" defaultValue={member.role}>{(isOwner?['admin','recruiter','hiring-manager','interviewer']:['recruiter','hiring-manager','interviewer']).map(r=><option key={r}>{r}</option>)}</select></label><label>Access<select name="status" defaultValue={member.status}><option value="active">Active</option><option value="disabled">Disabled — remove workspace access</option></select></label><Notice state={state}/><button disabled={pending}>{pending?'Saving…':'Save team access'}</button></form>;}
export function WorkspaceSwitcher({workspaces,current}) {const[state,action,pending]=useActionState(switchWorkspaceAction,{});return <form action={action}><label>Workspace<select name="workspace" defaultValue={current}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><Notice state={state}/><button disabled={pending}>Switch workspace</button></form>;}
