import Link from 'next/link';

export const metadata = { title: 'Privacy Notice | Recruit AI', description: 'How Recruit AI processes personal data.' };

const sections = [
  ['01', 'Personal data we process', 'Depending on use, this can include account and workspace details; candidate names and contact details; resumes, portfolios, employment history, education and skills; job descriptions and hiring criteria; application and interview responses; recordings or transcripts when an interview feature is used; and technical, security and audit information.'],
  ['02', 'Why we process it', 'We operate and secure the service, manage recruitment workflows, organise candidate evidence, schedule interviews, send service communications, prevent fraud and misuse, provide support and meet applicable legal obligations. We do not sell personal data to advertisers or data brokers.'],
  ['03', 'Who may receive it', 'Authorised members of the relevant hiring workspace may access recruitment information. Service providers may process data for hosting, storage, authentication, email, AI infrastructure and support. We may disclose data where a valid law, court order or regulator requires it.'],
  ['04', 'AI-assisted hiring', 'Recruit AI can extract resume information, transcribe interviews and create evidence-based summaries or matching signals. These outputs assist a hiring team and should not be the sole basis for a final hiring decision. The employer remains responsible for hiring decisions.'],
  ['05', 'Retention, deletion and security', 'We retain data only while it is needed for the hiring, account, security, dispute or legal purpose. On a valid deletion request, eligible data is removed or de-identified from active systems. Limited data may remain where required for law, security, fraud prevention, disputes or backup integrity.'],
  ['06', 'Your rights and requests', 'Where applicable under the Digital Personal Data Protection Act, 2023 and its rules, you may ask for information about processing, correction, erasure, consent withdrawal, grievance redressal and nomination. We may verify identity and may refer a request to the organisation that controls the relevant hiring process. Requests can be started through the Data Rights Desk.']
];

export default function PrivacyPage() { return <main className="legalLanding legalLandingPrivacy"><header className="legalSimpleNav"><Link href="/" className="legalBrand"><span className="legalBrandMark"><img src="/recruit-ai-logo.png" alt="" /></span><span>Recruit <i>AI</i></span></Link><nav><Link href="/terms">Terms</Link><Link className="legalNavButton" href="/grievance">Data rights</Link></nav></header><section className="legalHero" aria-labelledby="privacy-title"><div className="legalHeroGlow" /><div className="legalHeroInner"><span className="legalHeroKicker">RECRUIT AI / PRIVACY NOTICE</span><h1 id="privacy-title">A clear record of<br /><em>what happens to your data.</em></h1><p>What we collect, why we use it, who may receive it, how long we keep it and how you can ask for help.</p><div className="legalHeroActions"><Link href="#notice">Read the notice <span>↓</span></Link><Link className="legalHeroSecondary" href="/grievance">Make a data request</Link></div></div></section><article id="notice" className="legalDoc legalDocWide"><div className="legalMeta"><span>DPDP ACT / INFORMATION NOTICE</span><span>Last reviewed: 15 September 2026</span></div><p className="legalLead">Recruit AI provides recruitment software. This notice explains our data practices in plain language and does not reduce any right available under applicable law. Depending on the arrangement, the relevant hiring organisation or Recruit AI may determine the purpose of processing, and responsibilities may differ accordingly.</p><div className="legalNoticeGrid"><div><b>Specific purpose</b><span>We use data for stated service and hiring purposes.</span></div><div><b>No data sale</b><span>We do not sell data to advertisers or brokers.</span></div><div><b>Human accountability</b><span>People remain responsible for hiring decisions.</span></div></div><div className="legalSections">{sections.map(([number, title, text]) => <section key={number}><span className="legalSectionNo">{number}</span><div><h2>{title}</h2><p>{text}</p></div></section>)}</div><section className="legalCallout"><h2>Want to access, correct or erase data?</h2><p>Use the available data-rights request route. Identity may be verified before information is released or deleted, and any lawful limitation will be explained.</p><Link href="/grievance">Open Data Rights &amp; Erasure <span>↗</span></Link></section></article><footer className="legalFooter"><Link href="/">Recruit <i>AI</i></Link><span>Privacy notice for thoughtful hiring.</span><Link href="/grievance">Data rights ↗</Link></footer></main>; }
