'use client';
import {useEffect,useState} from 'react';
import DiscoveryTablet from './components/DiscoveryTablet';
import EvidenceQuote from './components/EvidenceQuote';
import AboutReveal from './components/AboutReveal';
import ReportsPreview from './ReportsPreview';
import {pricingPlans} from '../config/pricing';
import {AnimatePresence,motion,useScroll,useTransform} from 'framer-motion';
const features=[['▤','Resume Intelligence','Parses resumes against your role spec, flags evidence gaps and ranks candidates for review.','/56bbc202-b3bb-40c2-812c-e47486ef6264.jpg'],['◉','Live AI Interviews','Voice-enabled rounds that collect answers and signals your team can review.','/f6117bd6-8641-4670-910d-1cf2ce759193.jpg'],['♙','Candidate Discovery','Find ranked matches across your incoming candidates and configured talent sources.','/88e30a65-1f4c-4c59-ba4c-028a3ddd4f34.jpg'],['▥','Hiring Analytics','Review the activity and stage counts in your hiring pipeline.','/9db73c03-b5d3-4a71-8b38-460da5aa7c3e.jpg']];
const faqs=[['How does the AI screening actually work?','Your JD is turned into review criteria. Resume evidence is compared with those criteria, and recruiters can review the resulting breakdown.'],['Are the AI interviews recorded and reviewable?','Interview answers are stored as a reviewable transcript with an evaluation for the hiring team.'],['Can I use Recruit AI alongside my existing ATS?','Contact us to confirm compatibility with your current ATS and workflow.'],['What does Recruit AI cost?','Contact us for current pricing and an agreed scope based on your hiring needs.'],['Is my candidate data private and secure?','Records are scoped to a workspace, and the product includes a data-rights and erasure request route. Contact us for security and retention details.']];
const Arrow=()=> <b className="arrow">↗</b>;
const rise={hidden:{opacity:0,y:30,filter:'blur(8px)'},show:{opacity:1,y:0,filter:'blur(0px)'}};
function Reveal({children,delay=0,className=''}){return <motion.div className={className} variants={rise} initial="hidden" whileInView="show" viewport={{once:true,amount:.18}} transition={{duration:.7,delay,ease:[.16,1,.3,1]}}>{children}</motion.div>}
function HeroAura(){const {scrollY}=useScroll();const y=useTransform(scrollY,[0,650],[0,170]);const rotate=useTransform(scrollY,[0,650],[0,25]);return <motion.div className="heroAura" style={{y,rotate}}><i/><i/><i/><b>AI</b></motion.div>}
const heroMessages=['supports review.','organizes evidence.','keeps teams informed.'];
function HeroTypewriter(){const [message,setMessage]=useState(0);useEffect(()=>{const timer=setInterval(()=>setMessage(value=>(value+1)%heroMessages.length),5200);return()=>clearInterval(timer)},[]);return <strong className="heroTyped" aria-live="polite"><AnimatePresence mode="wait"><motion.span key={heroMessages[message]} initial={{opacity:0,x:-52,filter:'blur(12px)'}} animate={{opacity:1,x:0,filter:'blur(0px)',transition:{duration:3,ease:[.22,1,.36,1]}}} exit={{opacity:0,x:28,filter:'blur(7px)',transition:{duration:.45,ease:'easeIn'}}}>{heroMessages[message]}</motion.span></AnimatePresence></strong>}
function Logo(){return <a className="logo" href="#top"><span><img src="/recruit-ai-logo.png" alt="Recruit AI"/></span>Recruit <i>AI</i></a>}
export default function Page(){const [active,setActive]=useState(0),[open,setOpen]=useState(0),[menuOpen,setMenuOpen]=useState(false);const f=features[active];return <main id="top">
<header className="nav"><Logo/><nav><a href="#features">Features</a><a href="#services">Services</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a><a href="#articles">Articles</a></nav><div><a className="signin" href="/sign-in">Sign in</a><a className="darkButton" href="/contact">Request access</a><button className="menu" type="button" aria-label={menuOpen?"Close menu":"Open menu"} aria-expanded={menuOpen} aria-controls="landing-mobile-menu" onClick={()=>setMenuOpen(value=>!value)}>☰</button></div>{menuOpen&&<nav id="landing-mobile-menu" className="mobileLandingNav" aria-label="Mobile navigation"><a href="/sign-in" onClick={()=>setMenuOpen(false)}>Sign in</a>{["Features","Services","Pricing","FAQ","Articles"].map(label=><a key={label} href={"#"+label.toLowerCase()} onClick={()=>setMenuOpen(false)}>{label}</a>)}</nav>}</header>
<section className="hero"><div className="heroInner"><Reveal><div className="available"><b/><span><strong>Now accepting new hiring partners</strong></span></div></Reveal><motion.h1 initial="hidden" animate="show" variants={{hidden:{opacity:0,y:50},show:{opacity:1,y:0,transition:{duration:.9,ease:[.16,1,.3,1]}}}}><span><em>Recruitment</em> that</span><HeroTypewriter/></motion.h1><Reveal delay={.18}><p className="lede"><b>AI-assisted recruitment built around your role requirements.</b> Screen, interview and rank candidates in one workflow.</p><div className="heroBtns"><a className="gradientBtn" href="/demo"><em>AI</em>Book a demo with us <small>You</small></a><a className="outlineBtn" href="#features">See how it works</a></div><div className="chips"><span><b>Evidence-led</b> resume review</span><span><b>JD-based</b> scoring breakdowns</span><span><b>On-demand</b> AI interviews</span></div></Reveal></div></section>
<section id="features" className="featureSection"><Reveal><div className="sectionHead"><h2>Latest <strong>features</strong></h2><a href="#services">View all features <Arrow/></a></div></Reveal><div className="featureGrid"><div className="featureList">{features.map((x,i)=><motion.button whileHover={{x:7,scale:1.015}} whileTap={{scale:.98}} onClick={()=>setActive(i)} className={active===i?'selected':''} key={x[1]}><span className="featureIcon">{x[0]}</span><span><b>{x[1]}</b><small>AI Feature · {i===0?'Screening':i===1?'Rounds':i===2?'Sourcing':'Pipeline'}</small></span><i>›</i></motion.button>)}</div><motion.article style={{'--feature-image':`url("${f[3]}")`}} key={f[1]} initial={{opacity:0,y:18,scale:.97}} animate={{opacity:1,y:0,scale:1}} transition={{duration:.45,ease:[.16,1,.3,1]}} className={'featurePreview '+(active===0?'resumePreview':'')}><div className="dots"/><p className="tag"><b/> AI Feature · {active===0?'Screening':active===1?'Interviews':active===2?'Sourcing':'Analytics'}</p><span className="bigIcon">{f[0]}</span><h3>{f[1]}</h3><p>{f[2]}</p><a href="/demo" className="gradientBtn">Explore {f[1]} <Arrow/></a></motion.article></div></section>
<EvidenceQuote/>
<section id="services" className="services"><div><h2><span>Services that</span> support your hiring.</h2><p><b>Built into one recruitment workspace.</b> Review resumes, interviews and pipeline information together.</p><small>OUR STACK</small><div className="stack"><i className="next">N</i><i className="typescript">TS</i><i className="whisper">⌁</i><i className="openai">◎</i><i className="langchain">LC</i><i className="postgres">◒</i><i className="redis">◆</i></div></div><div className="serviceList">{['Resume Intelligence|Screening evidence organized against your JD','Live AI Interviews|Voice-enabled rounds with reviewable answers','Candidate Discovery|Ranked matches from configured talent sources','Hiring Analytics|Funnel and time-to-hire reporting','Interview Scheduling|Tools for coordinating interview rounds','Workspace Privacy|Workspace-scoped access and data-rights controls'].map((x,i)=>{let[a,b]=x.split('|');return <article key={a}><span>{['▤','◉','♙','▥','□','✓'][i]}</span><div><b>{a}</b><p>{b}</p></div><i>›</i></article>})}</div></section>
<section className="about"><h2><span>Building hiring</span> that feels human.</h2><div className="aboutGrid"><div className="founder"><div className="portrait"><img src="/aa].jpeg" alt="Recruit AI founder"/><small>Founders photo — Raipur, IN</small></div><p><span>◎ India-first</span><span>♙ Human-led</span><span>◌ Candidate-friendly</span></p></div><AboutReveal/></div></section>
<section id="pricing" className="pricing"><h2><span>Pricing shaped to</span> your hiring needs.</h2><p><b>Scope and usage are confirmed before purchase.</b> Contact us for current pricing.</p><div className="steps">{['Tell us your needs|Share the roles and workflow you want to support.','Confirm the scope|Agree capacity, features and pricing with our team.','Start with clarity|Use the agreed hiring workflow and review its outputs.'].map((x,i)=>{let[a,b]=x.split('|');return <article className={i===2?'stepDark':''} key={a}><strong>0{i+1}</strong><div><b>{a}</b><p>{b}</p></div></article>})}</div><div className="priceCards"><aside><div className="badge">Recruit <i>AI</i><b>AI</b><small>Hiring workflow software</small></div><h3>Discuss your hiring plan</h3><p>We will confirm the scope, usage limits and price before you commit.</p><span>● Contact our team</span></aside>{pricingPlans.map(plan=><article className={plan.className} key={plan.id}>{plan.className==='oneOff'&&<p>{plan.name}</p>}<h3>{plan.className==='pro'?<>{plan.name} <small>{plan.badge}</small></>:plan.price}</h3>{plan.className==='pro'&&<p>{plan.description}</p>}{plan.className==='pro'&&<h4>{plan.price}{plan.cadence&&<span>{plan.cadence}</span>}</h4>}{plan.className==='oneOff'&&<p>{plan.description}</p>}<ul>{plan.features.map(feature=><li key={feature}>✓ {feature}</li>)}</ul><a href={plan.ctaHref} className={plan.className==='pro'?'gradientBtn':undefined}>{plan.cta} <Arrow/></a></article>)}</div></section>
<section id="faq" className="faq"><div><h2><span>Your questions</span> answered.</h2><article><b>AI</b><p><strong>Still not sure?</strong><br/>Book a free demo call.</p><a className="gradientBtn" href="/demo">Book a demo <Arrow/></a></article></div><div className="faqList">{faqs.map((x,i)=><section className={open===i?'open':''} key={x[0]}><button onClick={()=>setOpen(open===i?-1:i)}><small>0{i+1}</small><b>{x[0]}</b><i>+</i></button>{open===i&&<p>{x[1]}</p>}</section>)}</div></section>
<section id="articles" className="articles"><div className="sectionHead"><h2>From our blog, <strong>hiring insights.</strong></h2><a>View all articles <Arrow/></a></div><div className="articleGrid"><article className="articleLead"><div>✦</div><span>Recruiting</span><h3>Building a more reviewable hiring pipeline</h3><p>A practical guide to combining screening evidence, interview review and human decisions.</p><b>Read article <Arrow/></b></article>{[['◌','Interview Design','Writing interview questions that don’t leak the answer','A checklist for asking focused questions without signalling the expected response.'],['▥','Data','Reading your funnel: which stage leaks the most talent?','A guide to reviewing stage counts and spotting where candidates leave the process.']].map(x=><article className="articleSmall" key={x[2]}><div>{x[0]}</div><p>{x[1]}</p><h3>{x[2]}</h3><span>{x[3]}</span></article>)}</div></section>
<section id="discovery" className="discovery"><div className="discoveryCopy"><Reveal><p className="discoveryEyebrow"><b/> CANDIDATE DISCOVERY</p><h2>Meet the right people <em>before they apply.</em></h2><p>Tell Recruit AI what great looks like. It searches your talent pool, understands career evidence and brings forward candidates worth your team’s time.</p><a className="lightButton" href="#pricing">Start discovering <Arrow/></a></Reveal><div className="discoveryNotes"><span>01 <b>Understand your role</b></span><span>02 <b>Search beyond keywords</b></span><span>03 <b>Review the evidence</b></span></div></div><DiscoveryTablet/></section>
<ReportsPreview/>
<footer><div><h2>Let’s <em>hire</em> incredible people, together.</h2><a href="mailto:hello@recruitai.com">✉ Email</a><a className="lightButton" href="/contact">Request access <Arrow/></a></div><nav><b>MENU</b><a href="#features">Features</a><a href="#services">Services</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><nav><b>ACCESS</b><a href="/sign-in">Sign in</a><a href="/contact">Request access</a><a href="/dashboard">Dashboard</a></nav><nav><b>LEGAL</b><a href="/privacy">Privacy Notice</a><a href="/grievance">Data rights & erasure</a><a href="/terms">Terms of Service</a></nav><nav><b>CONTACT</b><a>hello@recruitai.com</a><a>Raipur, IN</a></nav>{/* TODO_LEGAL_ENTITY: confirm the registered legal entity name before adding a suffix. */}<p>© 2026 Recruit AI. All rights reserved.</p><strong>RECRUIT AI</strong></footer>
</main>}
