import { candidateInterviews } from '../../../../lib/tech-dna-store';
import RetryTechDNA from './RetryTechDNA';
import '../../../interview/sireen.css';

function EvidenceRow({ item, sessionId }) {
  return <article className="dnaEvidenceRow"><div className="dnaBetween"><h4>{item.label}</h4><span className="dnaPill">{item.rating === null ? 'Not assessed' : `${item.rating} / 5`}</span></div><div className="dnaScale" aria-label={item.rating === null ? 'Not assessed' : `${item.rating} out of 5`}>{Array.from({length:5},(_,i)=><span className={item.rating!==null && i<item.rating?'filled':''} key={i}/>)}</div>{item.expectation && <p><strong>Role expectation:</strong> {item.expectation}</p>}<p>{item.finding}</p>{item.evidence.map((e,i)=><blockquote key={i}>“{e.quote}”<a href={`#${sessionId}-${e.question_id}`}>Read {e.question_id.toUpperCase()} in context →</a></blockquote>)}{item.probe && <p><strong>Verify next:</strong> {item.probe}</p>}</article>;
}
export default async function TechDNA({ workspaceId, candidateId, canManage }) {
  let sessions;
  try { sessions = await candidateInterviews(workspaceId,candidateId); } catch { return <div className="dnaReport"><div className="dnaEmpty">Interview data is temporarily unavailable. Please reload to retry.</div></div>; }
  return <div className="dnaReport"><header className="dnaReportHeader"><div><span className="dnaEyebrow">CANDIDATE INTELLIGENCE / TECH DNA</span><h2>Go beyond the first impression.</h2><p>A role-specific view of demonstrated capability, with the evidence and the limits in plain sight.</p></div><span className="dnaPill">{sessions.length} interview{sessions.length!==1?'s':''}</span></header>{!sessions.length && <div className="dnaEmpty">No Sireen interviews yet. Open a job, create an interview link and share it with this candidate. Completed answers and Tech DNA appear here.</div>}{sessions.map(session => <section key={session.id} className="dnaSession"><div className="dnaBetween"><h3>{session.blueprint.role}</h3><span className="dnaPill">{session.status} · {session.transcript.length}/5 answers</span></div><p className="dnaNotice">{new Date(session.created).toLocaleString('en-IN')} · {session.blueprint.version} · Rubric captured when invited</p>{session.events.length>0 && <div className="dnaReviewFlag"><strong>Needs human review · {session.events.length} session interruption{session.events.length!==1?'s':''}</strong><br/>{session.status==='terminated'?'Session ended after three distinct incidents. ':''}Browser events are not proof of cheating and do not change skill ratings.<details><summary>Review event timeline</summary><ol className="dnaEventList">{session.events.map(e=><li key={e.id}>{e.kind.replaceAll('_',' ')} · {new Date(e.created).toLocaleString('en-IN')}</li>)}</ol></details></div>}
    {session.dna ? <><div className="dnaReportGrid"><section className="dnaCard"><span className="dnaEyebrow">THE HR BRIEF</span><h2>What the evidence says</h2><p>{session.dna.summary}</p><span className="dnaPill">{session.dna.confidence}</span><p className="dnaNotice">Interview evidence describes demonstrated answers, not the person’s full nature or potential. Validate claims with a work sample; the hiring decision remains with your team.</p></section><section className="dnaCard"><span className="dnaEyebrow">DEMONSTRATED ROLE ALIGNMENT</span><div className="dnaMetric"><strong>{session.dna.score ?? '—'}</strong><span>/ 100 on assessed criteria</span></div><div className="dnaMeter"><span style={{width:`${session.dna.coverage}%`}}/></div><p>{session.dna.coverage}% weighted evidence coverage</p><p className="dnaNotice">The score excludes unknown criteria. Read it with coverage; it is not a hiring probability or a validated prediction of performance.</p></section></div><div className="dnaReportGrid"><section className="dnaCard"><span className="dnaEyebrow">JD → EVIDENCE</span><h2>Role requirements</h2>{session.dna.criteria.map(item=><EvidenceRow key={item.id} item={item} sessionId={session.id}/>)}</section><section className="dnaCard"><span className="dnaEyebrow">HOW THEY APPROACH THE WORK</span><h2>Capability signals</h2>{session.dna.dimensions.map(item=><EvidenceRow key={item.id} item={item} sessionId={session.id}/>)}</section></div><details className="dnaCard"><summary>How this Tech DNA is calculated</summary><p>Each assessed criterion uses a 1–5 anchored rubric: misconception, partial explanation, applied understanding, reasoned trade-offs, then deep reasoning with verification and limits. Only ratings with matching answer quotes are included. JD weights are frozen before the interview.</p><p>Alignment = weighted mean of assessed ratings ÷ 5 × 100. Coverage = assessed JD weight ÷ total JD weight. Missing evidence stays unknown. Browser events, resume prestige and personal characteristics are excluded from scores.</p><p className="dnaNotice">Model: {session.dna.model} · Version: {session.dna.version} · Generated: {new Date(session.dna.generated_at).toLocaleString('en-IN')}. AI findings can be wrong even when a quote matches; review the full context.</p></details></> : <section className="dnaCard"><h3>{['completed','terminated'].includes(session.status)?'Tech DNA is awaiting analysis':'Interview in progress'}</h3><p>Saved answers remain available below. Missing analysis is not a zero score.</p>{canManage && ['completed','terminated'].includes(session.status) && <RetryTechDNA sessionId={session.id} candidateId={candidateId}/>}</section>}
    <section className="dnaCard"><span className="dnaEyebrow">THE SOURCE OF TRUTH</span><h2>Full interview transcript</h2><p>Candidate-reviewed text answers. No audio or video recording.</p>{session.transcript.map((t,i)=><article className="dnaTranscript" id={`${session.id}-${t.id}`} key={t.id}><span className="dnaEyebrow">QUESTION {i+1} · {session.blueprint.criteria.find(c=>c.id===t.criterion_id)?.name}</span><h4>{t.prompt}</h4><p>{t.answer}</p><small>Submitted {new Date(t.answered_at).toLocaleString('en-IN')}</small></article>)}{!session.transcript.length && <p>No answers submitted yet.</p>}<details><summary>Resume context provided by the candidate</summary><pre className="dnaResumeText">{session.resume}</pre></details></section></section>)}</div>;
}
