'use client';

import { useRef, useState } from 'react';
import { useFormStatus } from 'react-dom';
import { sendOutreachAction } from './actions';

const templates = {
  custom: { label: 'Blank message', subject: '', body: '' },
  intro: { label: 'Role introduction', subject: 'A role that may interest you', body: 'Hi {{first_name}},<br><br>I came across your profile and thought your experience could be a strong fit for a role we are hiring for.<br><br>Would you be open to a quick conversation this week?<br><br>Best,' },
  followup: { label: 'Friendly follow-up', subject: 'Following up', body: 'Hi {{first_name}},<br><br>Just following up on my earlier note. I would be happy to share more context about the role if the timing is right.<br><br>Best,' },
  interview: { label: 'Interview invitation', subject: 'Invitation to speak with our team', body: 'Hi {{first_name}},<br><br>We would like to invite you to the next conversation with our team. Please share a time that works well for you.<br><br>Best,' },
};

function SendButton({ disabled }) { const { pending } = useFormStatus(); return <button className="outreachSend" disabled={disabled || pending}>{pending ? 'Sending…' : 'Send email'}</button>; }
function Icon({ name }) { const path = name==='mail'?'M3 5h18v14H3zM3 7l9 6 9-6':'M12 16v-8M8 12l4-4 4 4M5 20h14'; return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={path}/></svg>; }

export default function OutreachComposer({ initialChannel, initialRecipients, loginEmail, sendingAccount, notice }) {
  const [channel, setChannel] = useState(initialChannel);
  const [recipients, setRecipients] = useState(initialRecipients);
  const [recipientInput, setRecipientInput] = useState('');
  const [template, setTemplate] = useState('intro');
  const [subject, setSubject] = useState(templates.intro.subject);
  const [body, setBody] = useState(templates.intro.body.replaceAll('{{first_name}}', initialRecipients[0]?.name?.split(' ')[0] || 'there'));
  const [files, setFiles] = useState([]);
  const [linkedinDone, setLinkedinDone] = useState(false);
  const editorRef = useRef(null), fileRef = useRef(null);
  const available = channel === 'email' ? recipients.filter((item) => item.email) : recipients.filter((item) => item.linkedin);
  const messageText = body.replace(/<br\s*\/?>/gi, '\n').replace(/<[^>]+>/g, '');
  const noticeText = { sent: 'Email sent from your connected Gmail account.', incomplete: 'Add at least one valid recipient, a subject and a message.', 'account-required': 'Connect the same Google account you use to sign in before sending.', 'oauth-not-configured': 'Google mailbox connection is not configured for this environment.', 'oauth-cancelled': 'Google connection was cancelled. No account access was saved.', 'oauth-invalid': 'The connection request expired or could not be verified. Start again.', 'oauth-email-mismatch': `Connect ${loginEmail}, the same address used to sign in.`, 'oauth-failed': 'Google could not be connected. Check the OAuth configuration and retry.', 'account-connected': 'Google account connected. Emails will be sent from this mailbox.', 'account-disconnected': 'Sending account disconnected.', 'attachment-too-large': 'Each attachment must be 10 MB or smaller and the total must stay under 20 MB.', failed: 'Gmail could not send this message. Reconnect the account or try again.' }[notice];

  const applyTemplate = (key) => { const next = templates[key]; setTemplate(key); setSubject(next.subject); const html = next.body.replaceAll('{{first_name}}', recipients[0]?.name?.split(' ')[0] || 'there'); setBody(html); if (editorRef.current) editorRef.current.innerHTML = html; };
  const addRecipient = () => { const value = recipientInput.trim(); if (!value) return; setRecipients((current) => [...current, channel === 'email' ? { name: value.split('@')[0], email: value, linkedin: '' } : { name: 'Candidate', email: '', linkedin: value }]); setRecipientInput(''); };
  const format = (command, value) => { editorRef.current?.focus(); document.execCommand(command, false, value); setBody(editorRef.current?.innerHTML || ''); };
  const openLinkedIn = async () => { try { await navigator.clipboard.writeText(messageText); setLinkedinDone(true); available.forEach((item, index) => setTimeout(() => window.open(item.linkedin, '_blank', 'noopener,noreferrer'), index * 180)); } catch { setLinkedinDone(false); } };

  return <div className="outreachPage">
    <header className="outreachHeading"><div><p>Candidate outreach</p><h1>Start a conversation.</h1><span>Write once, personalize, and reach candidates in the right channel.</span></div><div className="channelSwitch" aria-label="Outreach channel"><button type="button" aria-pressed={channel==='email'} onClick={()=>setChannel('email')}><Icon name="mail"/>Email</button><button type="button" aria-pressed={channel==='linkedin'} onClick={()=>setChannel('linkedin')}><span aria-hidden="true">in</span>LinkedIn</button></div></header>
    {noticeText&&<div className={`outreachNotice ${notice==='sent'?'success':''}`} role="status">{noticeText}</div>}
    {channel==='email'&&<section className="senderAccount"><div><span className={`connectionDot ${sendingAccount?'connected':''}`} aria-hidden="true"/><div><small>Send as</small><strong>{sendingAccount?.email || 'No mailbox connected'}</strong><p>{sendingAccount?'Messages are saved in this Gmail account’s Sent folder.':`Connect ${loginEmail} to send from your own address.`}</p></div></div>{sendingAccount?<form action="/api/outreach/disconnect" method="post"><button type="submit">Disconnect</button></form>:<a className="connectAccount" href="/api/outreach/google/connect">Connect Google account</a>}</section>}
    <form action={sendOutreachAction} className="composerCard" onSubmit={(event)=>{if(channel==='linkedin')event.preventDefault();}}>
      <section className="recipientArea" aria-labelledby="recipient-label"><div className="composerLabel"><span id="recipient-label">{channel==='email'?'To':'LinkedIn profiles'}</span><small>{available.length} ready</small></div><div className="recipientInputWrap">{available.map((person)=><span className="recipientChip" key={(channel==='email'?person.email:person.linkedin)}>{person.name}<button type="button" aria-label={`Remove ${person.name}`} onClick={()=>setRecipients(items=>items.filter(item=>item!==person))}>×</button><input type="hidden" name={channel==='email'?'recipients':'profiles'} value={channel==='email'?person.email:person.linkedin}/></span>)}<input aria-label={channel==='email'?'Add recipient email':'Add LinkedIn profile URL'} type={channel==='email'?'email':'url'} value={recipientInput} onChange={e=>setRecipientInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'||e.key===','){e.preventDefault();addRecipient();}}} onBlur={addRecipient} placeholder={available.length?'Add another…':channel==='email'?'name@company.com':'linkedin.com/in/…'}/></div>{recipients.length>available.length&&<p className="recipientWarning">{recipients.length-available.length} selected candidate{recipients.length-available.length===1?' is':'s are'} missing a {channel==='email'?'verified email':'LinkedIn profile'} and won’t be included.</p>}</section>
      <div className="composeMeta"><label>Template<select value={template} onChange={e=>applyTemplate(e.target.value)}>{Object.entries(templates).map(([key,item])=><option key={key} value={key}>{item.label}</option>)}</select></label><p>Send as <strong>{sendingAccount?.email || 'Connect account first'}</strong></p></div>
      {channel==='email'&&<label className="subjectField"><span>Subject</span><input name="subject" maxLength={200} required value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What’s this message about?"/></label>}
      <section className="editorShell"><div className="formatBar" role="toolbar" aria-label="Text formatting"><button type="button" onClick={()=>format('bold')} aria-label="Bold"><b>B</b></button><button type="button" onClick={()=>format('italic')} aria-label="Italic"><i>I</i></button><button type="button" onClick={()=>format('underline')} aria-label="Underline"><u>U</u></button><span/><button type="button" onClick={()=>format('insertUnorderedList')} aria-label="Bulleted list">• List</button><button type="button" onClick={()=>format('insertOrderedList')} aria-label="Numbered list">1. List</button><button type="button" onClick={()=>{const url=window.prompt('Link URL');if(url)format('createLink',url);}} aria-label="Add link">Link</button><button type="button" onClick={()=>format('removeFormat')} aria-label="Clear formatting">Clear</button></div><div ref={editorRef} className="messageEditor" contentEditable suppressContentEditableWarning role="textbox" aria-multiline="true" aria-label="Message" onInput={e=>setBody(e.currentTarget.innerHTML)} dangerouslySetInnerHTML={{__html:body}}/><input type="hidden" name="body" value={body}/></section>
      {channel==='email'&&<label className="outreachBasis"><input type="checkbox" name="outreachBasis" value="confirmed" required/><span>I confirm these recipients can be contacted for this role and any opt-out or do-not-contact request has been respected.</span></label>}
      <div className="composerFooter"><div className="attachmentArea">{channel==='email'&&<><input ref={fileRef} className="srOnly" type="file" name="attachments" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,5))}/><button type="button" onClick={()=>fileRef.current?.click()}><Icon name="upload"/>Attach files</button>{files.length>0&&<span>{files.length} file{files.length===1?'':'s'} attached</span>}</>}</div><span className="messageCount">{messageText.length.toLocaleString()} characters</span>{channel==='email'?<SendButton disabled={!sendingAccount||!available.length||!subject.trim()||!messageText.trim()}/>:<button type="button" className="outreachSend linkedinSend" disabled={!available.length||!messageText.trim()} onClick={openLinkedIn}>{linkedinDone?'Message copied — profiles opened':'Copy message & open LinkedIn'}</button>}</div>
    </form>
    <aside className="deliveryNote"><strong>{channel==='email'?'How delivery works':'LinkedIn API status'}</strong><p>{channel==='email'?<>Recruit AI uses the minimum Gmail send-only permission. Messages are sent as <b>{sendingAccount?.email || loginEmail}</b>; Recruit AI cannot read the inbox.</>:<>Direct recruiting DMs cannot be enabled with ordinary LinkedIn sign-in. LinkedIn restricts its messaging APIs and its Marketing API terms prohibit recruiting and mass-message use cases. Until Recruit AI receives approved partner access, the safe workflow copies the message and opens the selected profiles for your final review and send.</>}</p></aside>
  </div>;
}
