migrate((app) => {
  const w=app.findCollectionByNameOrId('workspaces'),c=app.findCollectionByNameOrId('candidates'),j=app.findCollectionByNameOrId('jobs');
  const locked={listRule:null,viewRule:null,createRule:null,updateRule:null,deleteRule:null};
  const audit=[{type:'autodate',name:'created',onCreate:true},{type:'autodate',name:'updated',onCreate:true,onUpdate:true}];
  const subscriptions=new Collection({type:'base',name:'workspace_subscriptions',...locked,fields:[
    {type:'relation',name:'workspace',collectionId:w.id,required:true,cascadeDelete:true,maxSelect:1},{type:'text',name:'provider',required:true,max:30},{type:'text',name:'customer_id',max:120},{type:'text',name:'subscription_id',max:120},{type:'text',name:'product_id',max:120},{type:'select',name:'plan',required:true,maxSelect:1,values:['free','pro']},{type:'select',name:'status',required:true,maxSelect:1,values:['free','pending','active','on-hold','cancelled','expired']},{type:'date',name:'current_period_end'},{type:'json',name:'entitlements'},{type:'text',name:'last_event_id',max:160},...audit],indexes:['CREATE UNIQUE INDEX idx_workspace_subscription ON workspace_subscriptions (workspace)','CREATE UNIQUE INDEX idx_dodo_subscription ON workspace_subscriptions (subscription_id)']});app.save(subscriptions);
  const vetting=new Collection({type:'base',name:'candidate_vetting',...locked,fields:[{type:'relation',name:'workspace',collectionId:w.id,required:true,cascadeDelete:true,maxSelect:1},{type:'relation',name:'candidate',collectionId:c.id,required:true,cascadeDelete:true,maxSelect:1},{type:'relation',name:'job',collectionId:j.id,cascadeDelete:true,maxSelect:1},{type:'select',name:'kind',required:true,maxSelect:1,values:['identity','education','employment','reference','work-sample','technical']},{type:'select',name:'status',required:true,maxSelect:1,values:['not-started','requested','candidate-provided','reviewed','verified','rejected']},{type:'text',name:'reviewer_clerk_user_id',max:120},{type:'text',name:'evidence',max:3000},{type:'json',name:'artifacts'},{type:'date',name:'reviewed_at'},...audit],indexes:['CREATE INDEX idx_candidate_vetting ON candidate_vetting (workspace,candidate)']});app.save(vetting);
  const performance=new Collection({type:'base',name:'talent_performance',...locked,fields:[{type:'relation',name:'workspace',collectionId:w.id,required:true,cascadeDelete:true,maxSelect:1},{type:'relation',name:'candidate',collectionId:c.id,required:true,cascadeDelete:true,maxSelect:1},{type:'relation',name:'job',collectionId:j.id,cascadeDelete:true,maxSelect:1},{type:'date',name:'period_start',required:true},{type:'date',name:'period_end',required:true},{type:'number',name:'quality_score',min:0,max:100},{type:'number',name:'reliability_score',min:0,max:100},{type:'number',name:'delivery_score',min:0,max:100},{type:'number',name:'hours'},{type:'number',name:'completed_tasks'},{type:'number',name:'rework_tasks'},{type:'text',name:'reviewer_clerk_user_id',required:true,max:120},{type:'text',name:'notes',max:5000},...audit],indexes:['CREATE INDEX idx_talent_performance ON talent_performance (workspace,candidate,period_end)']});app.save(performance);
},(app)=>{for(const n of ['talent_performance','candidate_vetting','workspace_subscriptions'])try{app.delete(app.findCollectionByNameOrId(n))}catch(_){}});
