'use client';

import Link from 'next/link';
import { useActionState, useEffect, useState, useTransition } from 'react';
import { createJobAction, generateJobContentAction, updateJobAction } from './actions';

const blank = { title: '', department: '', location: '', workplace_type: '', employment_type: '', openings: '1', experience_min: '0', experience_max: '', hiring_manager_name: '', hiring_manager_email: '', target_hire_date: '', priority: 'normal', salary_min: '', salary_max: '', currency: 'INR', must_have_skills: '', nice_to_have_skills: '', knockout_criteria: '', responsibilities: '', description: '' };
const stepLabels = ['Role basics', 'Candidate profile', 'Job context', 'Review'];

function ErrorText({ state, name }) {
  return state?.fieldErrors?.[name] ? <small className="fieldError">{state.fieldErrors[name]}</small> : null;
}

export default function JobForm({ initialJob = null }) {
  const editing = Boolean(initialJob?.id);
  const action = editing ? updateJobAction : createJobAction;
  const [state, formAction, pending] = useActionState(action, { error: '', fieldErrors: {} });
  const [step, setStep] = useState(0);
  const [localError, setLocalError] = useState('');
  const [generating, startGeneration] = useTransition();
  const [data, setData] = useState(() => ({ ...blank, ...(initialJob || {}), must_have_skills: (initialJob?.must_have_skills || []).join('\n'), nice_to_have_skills: (initialJob?.nice_to_have_skills || []).join('\n'), knockout_criteria: (initialJob?.knockout_criteria || []).join('\n'), target_hire_date: initialJob?.target_hire_date?.slice(0, 10) || '' }));
  useEffect(() => {
    const errors = Object.keys(state?.fieldErrors || {});
    if (!errors.length) return;
    const basic = ['title','department','location','workplace_type','employment_type','openings','priority'];
    const profile = ['experience_min','experience_max','must_have_skills','nice_to_have_skills','knockout_criteria'];
    setStep(basic.includes(errors[0]) ? 0 : profile.includes(errors[0]) ? 1 : 2);
    setLocalError('');
  }, [state]);
  const update = (name, value) => setData((current) => ({ ...current, [name]: value }));
  const fieldClass = (name) => state?.fieldErrors?.[name] ? 'hasError' : '';
  function generateContent() { setLocalError(''); startGeneration(async () => { const result = await generateJobContentAction(data); if (result?.error) { setLocalError(result.error); return; } setData((current) => ({ ...current, responsibilities: result.responsibilities, description: result.description })); }); }

  function continueStep(event) {
    event.preventDefault();
    let valid = true;
    if (step === 0) valid = data.title.trim().length >= 2 && data.department && data.location && data.workplace_type && data.employment_type && Number(data.openings) >= 1;
    if (step === 1) valid = data.experience_min !== '' && data.experience_max !== '' && Number(data.experience_max) >= Number(data.experience_min) && data.must_have_skills.trim();
    if (step === 2) valid = data.responsibilities.trim().length >= 40 && data.description.trim().length >= 80;
    if (!valid) { setLocalError('Complete the required information before continuing. You can still save the job as a draft.'); return; }
    setLocalError(''); setStep((current) => Math.min(3, current + 1));
  }

  return (
    <form action={formAction} className="jobFormShell" noValidate>
      {editing && <input type="hidden" name="jobId" value={initialJob.id} />}
      {Object.entries(data).map(([name, value]) => <input key={name} type="hidden" name={name} value={value ?? ''} />)}
      <aside className="jobFormSteps"><p>JOB INTAKE</p><h2>{editing ? 'Edit hiring brief' : 'Create a hiring brief'}</h2><ol>{stepLabels.map((label, index) => <li key={label} className={index === step ? 'active' : index < step ? 'done' : ''}><span>{index < step ? '✓' : index + 1}</span><b>{label}</b></li>)}</ol><div><b>Why structured intake?</b><p>Clear criteria now makes screening and interview evidence defensible later.</p></div></aside>
      <div className="jobFormMain">
        <div className="jobFormTop"><Link href={editing ? `/dashboard/jobs/${initialJob.id}` : '/dashboard/jobs'}>&larr; Cancel</Link><span>Step {step + 1} of 4</span></div>
        <div className="jobProgress"><span style={{ width: `${((step + 1) / 4) * 100}%` }} /></div>

        {step === 0 && <section className="jobFormStage"><p className="pageEyebrow">ROLE BASICS</p><h1>What are you hiring for?</h1><p>Start with the information candidates and your hiring team need to identify this role.</p><label>Job title <em>Required</em><input className={fieldClass('title')} value={data.title} onChange={(e) => update('title', e.target.value)} placeholder="Senior Backend Engineer" autoFocus /><ErrorText state={state} name="title" /></label><div className="jobFieldGrid"><label>Department <em>Required</em><input className={fieldClass('department')} value={data.department} onChange={(e) => update('department', e.target.value)} placeholder="Engineering" /><ErrorText state={state} name="department" /></label><label>Number of openings <em>Required</em><input className={fieldClass('openings')} type="number" min="1" max="500" value={data.openings} onChange={(e) => update('openings', e.target.value)} /><ErrorText state={state} name="openings" /></label><label>Hiring location <em>Required</em><input className={fieldClass('location')} value={data.location} onChange={(e) => update('location', e.target.value)} placeholder="Bengaluru, India" /><ErrorText state={state} name="location" /></label><label>Workplace type <em>Required</em><select className={fieldClass('workplace_type')} value={data.workplace_type} onChange={(e) => update('workplace_type', e.target.value)}><option value="">Select type</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="onsite">On-site</option></select><ErrorText state={state} name="workplace_type" /></label><label>Employment type <em>Required</em><select className={fieldClass('employment_type')} value={data.employment_type} onChange={(e) => update('employment_type', e.target.value)}><option value="">Select type</option><option value="full-time">Full-time</option><option value="part-time">Part-time</option><option value="contract">Contract</option><option value="internship">Internship</option><option value="temporary">Temporary</option></select><ErrorText state={state} name="employment_type" /></label><label>Priority <em>Required</em><select value={data.priority} onChange={(e) => update('priority', e.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div></section>}

        {step === 1 && <section className="jobFormStage"><p className="pageEyebrow">CANDIDATE PROFILE</p><h1>Define what good looks like.</h1><p>Separate mandatory evidence from preferences so candidates are reviewed consistently.</p><div className="jobFieldGrid"><label>Minimum experience (years) <em>Required</em><input className={fieldClass('experience_min')} type="number" min="0" max="60" value={data.experience_min} onChange={(e) => update('experience_min', e.target.value)} /><ErrorText state={state} name="experience_min" /></label><label>Maximum experience (years) <em>Required</em><input className={fieldClass('experience_max')} type="number" min="0" max="60" value={data.experience_max} onChange={(e) => update('experience_max', e.target.value)} /><ErrorText state={state} name="experience_max" /></label></div><label>Must-have skills <em>One per line</em><textarea className={fieldClass('must_have_skills')} value={data.must_have_skills} onChange={(e) => update('must_have_skills', e.target.value)} rows="5" placeholder={'Node.js\nPostgreSQL\nSystem design'} /><ErrorText state={state} name="must_have_skills" /></label><label>Nice-to-have skills <small>Optional, one per line</small><textarea value={data.nice_to_have_skills} onChange={(e) => update('nice_to_have_skills', e.target.value)} rows="4" placeholder={'AWS\nKafka'} /></label><label>Knockout criteria <small>Optional, one per line</small><textarea value={data.knockout_criteria} onChange={(e) => update('knockout_criteria', e.target.value)} rows="4" placeholder="Must be available for the required working hours" /></label><div className="profileAiCard"><div><small>AI JOB DRAFT</small><b>Turn these requirements into a JD.</b><span>Generates editable responsibilities and description from this brief.</span></div><button className="aiGenerateButton" type="button" onClick={generateContent} disabled={generating || !data.title || !data.must_have_skills.trim()}>{generating ? 'Generating…' : '✦ Generate JD with AI'}</button></div></section>}

        {step === 2 && <section className="jobFormStage jobContextStage"><div className="contextHeading"><div><p className="pageEyebrow">JOB CONTEXT</p><h1>Build the candidate-facing brief.</h1><p>Generate a strong first draft from the requirements you already entered, then edit it in your voice.</p></div><button className="aiGenerateButton" type="button" onClick={generateContent} disabled={generating || !data.title || !data.must_have_skills.trim()}>{generating ? 'Generating…' : '✦ Generate with AI'}</button></div><div className="aiContextNote"><span>AI DRAFT</span><p>Uses role, location, experience, skills and criteria from steps 1–2. Nothing is saved until you review and publish.</p></div><div className="contextEditorGrid"><label>Responsibilities <em>Required</em><textarea className={fieldClass('responsibilities')} value={data.responsibilities} onChange={(e) => update('responsibilities', e.target.value)} rows="6" placeholder="Describe the outcomes this person will own..." /><ErrorText state={state} name="responsibilities" /></label><label>Job description <em>Required</em><textarea className={fieldClass('description')} value={data.description} onChange={(e) => update('description', e.target.value)} rows="6" placeholder="Describe the team, role, impact and candidate experience..." /><ErrorText state={state} name="description" /></label></div><details className="jobDetailsPanel"><summary>Additional job details <span>Manager, target date and salary</span></summary><div className="jobFieldGrid"><label>Hiring manager name <small>Optional</small><input value={data.hiring_manager_name} onChange={(e) => update('hiring_manager_name', e.target.value)} /></label><label>Hiring manager email <small>Optional</small><input className={fieldClass('hiring_manager_email')} type="email" value={data.hiring_manager_email} onChange={(e) => update('hiring_manager_email', e.target.value)} /><ErrorText state={state} name="hiring_manager_email" /></label><label>Target hire date <small>Optional</small><input type="date" value={data.target_hire_date} onChange={(e) => update('target_hire_date', e.target.value)} /></label><label>Currency <small>ISO code</small><input className={fieldClass('currency')} maxLength="3" value={data.currency} onChange={(e) => update('currency', e.target.value.toUpperCase())} /></label><label>Minimum annual salary <small>Optional</small><input className={fieldClass('salary_min')} type="number" min="0" value={data.salary_min} onChange={(e) => update('salary_min', e.target.value)} /></label><label>Maximum annual salary <small>Optional</small><input className={fieldClass('salary_max')} type="number" min="0" value={data.salary_max} onChange={(e) => update('salary_max', e.target.value)} /></label></div></details></section>}

        {step === 3 && <section className="jobFormStage jobReview"><p className="pageEyebrow">REVIEW</p><h1>Review the hiring brief.</h1><p>Publish when the criteria are ready for candidate evaluation, or keep it as a draft.</p><div className="reviewHero"><div><small>ROLE</small><h2>{data.title || 'Untitled role'}</h2><p>{data.department} &middot; {data.location} &middot; {data.workplace_type}</p></div><mark>{data.priority}</mark></div><div className="reviewColumns"><dl><div><dt>Employment</dt><dd>{data.employment_type}</dd></div><div><dt>Openings</dt><dd>{data.openings}</dd></div><div><dt>Experience</dt><dd>{data.experience_min}–{data.experience_max} years</dd></div><div><dt>Target date</dt><dd>{data.target_hire_date || 'Not set'}</dd></div></dl><div><h3>Must-have skills</h3><div className="skillTags">{data.must_have_skills.split(/[\n,]/).filter(Boolean).map((skill) => <span key={skill}>{skill.trim()}</span>)}</div><h3>Knockout criteria</h3><ul>{data.knockout_criteria.split(/[\n,]/).filter(Boolean).map((item) => <li key={item}>{item.trim()}</li>)}{!data.knockout_criteria.trim() && <li>None defined</li>}</ul></div></div></section>}

        {Object.entries(state?.fieldErrors || {}).length > 0 && <ul className="formError" role="alert">{Object.entries(state.fieldErrors).map(([name,message]) => <li key={name}>{message}</li>)}</ul>}
        {(localError || state?.error) && <p className="formError" role="alert">{localError || state.error}</p>}
        <footer className="jobFormActions"><button className="draftButton" name="intent" value="draft" type="submit" disabled={pending}>{pending ? 'Saving...' : 'Save as draft'}</button><div>{step > 0 && <button className="secondaryAction" type="button" onClick={() => { setLocalError(''); setStep((value) => value - 1); }}>&larr; Back</button>}{step < 3 ? <button className="primaryAction" type="button" onClick={continueStep}>Continue <span>&rarr;</span></button> : <button className="primaryAction" name="intent" value="publish" type="submit" disabled={pending}>{editing ? 'Save and publish' : 'Create and publish'} <span>&rarr;</span></button>}</div></footer>
      </div>
    </form>
  );
}
