import Link from 'next/link'; import { notFound } from 'next/navigation';
import { canManageJobs, getCandidateForWorkspace, getJobForWorkspace, getLatestCandidateJobEvaluation, listJobActivities, listJobApplications } from '../../../../lib/recruit-data';
import { requireWorkspace } from '../../../../lib/workspace-page'; import { changeJobStatusAction } from '../actions';
const date = (value) => value ? new Date(value).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Not set';
const labels = { draft: 'Draft', open: 'Open', paused: 'Paused', closed: 'Closed', archived: 'Archived' };
export default async function JobPage({ params }) {
  const { jobId } = await params; const { workspace, membership } = await requireWorkspace(); const job = await getJobForWorkspace(workspace.id, jobId); if (!job) notFound();
  const [applications, activities] = await Promise.all([listJobApplications(workspace.id, job.id), listJobActivities(workspace.id, job.id)]);
  const pipeline = await Promise.all((applications.items || []).map(async (application) => ({ application, candidate: await getCandidateForWorkspace(workspace.id, application.candidate), evaluation: await getLatestCandidateJobEvaluation(workspace.id, job.id, application.candidate) })));
  const canManage = canManageJobs(membership); const transitions = job.status === 'draft' ? ['open', 'archived'] : job.status === 'open' ? ['paused', 'closed', 'archived'] : job.status === 'paused' ? ['open', 'closed', 'archived'] : job.status === 'closed' ? ['open', 'archived'] : ['draft'];
  return <div className="productPage jobWorkspace"><Link className="backLink" href="/dashboard/jobs">&larr; All jobs</Link>
    <header className="jobWorkspaceHeader"><div><div className="jobTitleLine"><h1>{job.title}</h1><mark className={`jobStatus ${job.status}`}>{labels[job.status] || job.status}</mark></div><p>{job.department || 'No department'} &middot; {job.location || 'No location'} &middot; {job.workplace_type || 'Workplace not set'}</p></div>{canManage && <div className="jobHeaderActions"><Link className="primaryAction" href={`/dashboard/jobs/${job.id}/interview-link`}>Create interview <span>&rarr;</span></Link>{transitions.map((status) => <form action={changeJobStatusAction} key={status}><input type="hidden" name="jobId" value={job.id}/><input type="hidden" name="status" value={status}/><button className={status === 'open' ? 'primaryAction' : ''} type="submit">{status === 'open' ? 'Publish / reopen' : status === 'draft' ? 'Restore to draft' : status}</button></form>)}</div>}</header>
    <nav className="jobTabs"><a className="active" href="#overview">Overview</a><a href="#pipeline">Pipeline <span>{applications.totalItems || 0}</span></a><a href="#activity">Activity</a></nav>
    <div className="jobWorkspaceGrid" id="overview"><main><section className="surfaceCard jobSection"><div className="sectionTitle"><div><small>HIRING CRITERIA</small><h2>Candidate profile</h2></div><span>{job.experience_min ?? 0}–{job.experience_max ?? '—'} years</span></div><h3>Must-have skills</h3><div className="skillTags">{job.must_have_skills?.length ? job.must_have_skills.map((skill) => <span key={skill}>{skill}</span>) : <p>Not defined</p>}</div><h3>Nice-to-have skills</h3><div className="skillTags mutedTags">{job.nice_to_have_skills?.length ? job.nice_to_have_skills.map((skill) => <span key={skill}>{skill}</span>) : <p>None defined</p>}</div><h3>Knockout criteria</h3>{job.knockout_criteria?.length ? <ul>{job.knockout_criteria.map((criterion) => <li key={criterion}>{criterion}</li>)}</ul> : <p className="emptyCopy">None defined</p>}</section>
      <section className="surfaceCard jobSection"><small>ROLE CONTEXT</small><h2>Responsibilities</h2><p className="longCopy">{job.responsibilities || 'Not defined'}</p><h2>Job description</h2><p className="longCopy">{job.description || 'Not defined'}</p></section>
      <section className="surfaceCard jobSection" id="pipeline"><div className="sectionTitle"><div><small>PIPELINE</small><h2>Applications</h2></div><span>{applications.totalItems || 0}</span></div>{pipeline.length ? <div className="jobCandidateList">{pipeline.map(({ application, candidate, evaluation }) => candidate && <Link href={`/dashboard/jobs/${job.id}/candidates/${candidate.id}/evaluation`} key={application.id}><div className="candidateIdentity"><b className="candidateAvatar">{`${candidate.first_name?.[0] || ''}${candidate.last_name?.[0] || ''}`}</b><div><strong>{candidate.preferred_name || [candidate.first_name, candidate.last_name].filter(Boolean).join(' ')}</strong><small>{candidate.current_title || candidate.email}</small></div></div><mark>{application.stage}</mark><span>{evaluation?.status === 'completed' ? `${evaluation.overall_score}/100` : evaluation?.status || 'Evaluate'}</span><i>&rarr;</i></Link>)}</div> : <div className="inlineEmpty"><b>No candidates in this role yet.</b><p>Add a candidate and attach them to this job to begin evidence-based evaluation.</p></div>}</section>
    </main><aside><section className="surfaceCard jobFacts"><small>ROLE DETAILS</small><dl><div><dt>Openings</dt><dd>{job.openings || '—'}</dd></div><div><dt>Employment</dt><dd>{job.employment_type || '—'}</dd></div><div><dt>Priority</dt><dd>{job.priority || 'normal'}</dd></div><div><dt>Target hire date</dt><dd>{date(job.target_hire_date)}</dd></div><div><dt>Hiring manager</dt><dd>{job.hiring_manager_name || 'Not assigned'}</dd></div><div><dt>Salary</dt><dd>{job.salary_min !== null && job.salary_min !== '' ? `${job.currency} ${Number(job.salary_min).toLocaleString('en-IN')} – ${Number(job.salary_max).toLocaleString('en-IN')}` : 'Not disclosed'}</dd></div><div><dt>Created</dt><dd>{date(job.created)}</dd></div><div><dt>Updated</dt><dd>{date(job.updated)}</dd></div></dl></section><section className="surfaceCard jobFacts" id="activity"><small>RECENT ACTIVITY</small>{activities.items?.length ? <ol className="activityList">{activities.items.map((activity) => <li key={activity.id}><b>{activity.action.replaceAll('.', ' ')}</b><span>{date(activity.created)}</span></li>)}</ol> : <p className="emptyCopy">No activity recorded.</p>}</section></aside></div>
  </div>;
}
